/* eslint-disable import/no-unresolved */
/* This file is generated by scripts/generate-icon-registry.mjs */

import type { FC } from "react";
import type { SvgProps } from "react-native-svg";

import IconAsset0 from "../../../assets/icons/Icon-1.svg";
import IconAsset1 from "../../../assets/icons/Icon-16-Arrow.svg";
import IconAsset2 from "../../../assets/icons/Icon-16-Bullet_correct.svg";
import IconAsset3 from "../../../assets/icons/Icon-16-Bullet_dot.svg";
import IconAsset4 from "../../../assets/icons/Icon-16-Bullet_wrong.svg";
import IconAsset5 from "../../../assets/icons/Icon-16-Info.svg";
import IconAsset6 from "../../../assets/icons/Icon-16-premium-small.svg";
import IconAsset7 from "../../../assets/icons/Icon-2.svg";
import IconAsset8 from "../../../assets/icons/Icon-24-AI.svg";
import IconAsset9 from "../../../assets/icons/Icon-24-Alert.svg";
import IconAsset10 from "../../../assets/icons/Icon-24-Back.svg";
import IconAsset11 from "../../../assets/icons/Icon-24-Basket.svg";
import IconAsset12 from "../../../assets/icons/Icon-24-Bolt.svg";
import IconAsset13 from "../../../assets/icons/Icon-24-Book.svg";
import IconAsset14 from "../../../assets/icons/Icon-24-Calendar.svg";
import IconAsset15 from "../../../assets/icons/Icon-24-Check.svg";
import IconAsset16 from "../../../assets/icons/Icon-24-Checkbox.svg";
import IconAsset17 from "../../../assets/icons/Icon-24-Chevron.svg";
import IconAsset18 from "../../../assets/icons/Icon-24-Close.svg";
import IconAsset19 from "../../../assets/icons/Icon-24-Download.svg";
import IconAsset20 from "../../../assets/icons/Icon-24-Exam.svg";
import IconAsset21 from "../../../assets/icons/Icon-24-Flag.svg";
import IconAsset22 from "../../../assets/icons/Icon-24-Home.svg";
import IconAsset23 from "../../../assets/icons/Icon-24-Language.svg";
import IconAsset24 from "../../../assets/icons/Icon-24-Like.svg";
import IconAsset25 from "../../../assets/icons/Icon-24-Lock.svg";
import IconAsset26 from "../../../assets/icons/Icon-24-Map.svg";
import IconAsset27 from "../../../assets/icons/Icon-24-Moon.svg";
import IconAsset28 from "../../../assets/icons/Icon-24-Play.svg";
import IconAsset29 from "../../../assets/icons/Icon-24-Problem.svg";
import IconAsset30 from "../../../assets/icons/Icon-24-Profile.svg";
import IconAsset31 from "../../../assets/icons/Icon-24-Repeat.svg";
import IconAsset32 from "../../../assets/icons/Icon-24-Replay.svg";
import IconAsset33 from "../../../assets/icons/Icon-24-Search.svg";
import IconAsset34 from "../../../assets/icons/Icon-24-Star.svg";
import IconAsset35 from "../../../assets/icons/Icon-24-Start.svg";
import IconAsset36 from "../../../assets/icons/Icon-24-Sun.svg";
import IconAsset37 from "../../../assets/icons/Icon-24-Timer.svg";
import IconAsset38 from "../../../assets/icons/Icon-24-Trainer.svg";
import IconAsset39 from "../../../assets/icons/Icon-24-Trend.svg";
import IconAsset40 from "../../../assets/icons/Icon-24-Warning.svg";
import IconAsset41 from "../../../assets/icons/Icon-24-Zoom.svg";
import IconAsset42 from "../../../assets/icons/Icon-24-brain.svg";
import IconAsset43 from "../../../assets/icons/Icon-24-chart.svg";
import IconAsset44 from "../../../assets/icons/Icon-24-checkmark.svg";
import IconAsset45 from "../../../assets/icons/Icon-24-cup.svg";
import IconAsset46 from "../../../assets/icons/Icon-24-document.svg";
import IconAsset47 from "../../../assets/icons/Icon-24-flame.svg";
import IconAsset48 from "../../../assets/icons/Icon-24-list.svg";
import IconAsset49 from "../../../assets/icons/Icon-24-new.svg";
import IconAsset50 from "../../../assets/icons/Icon-24-notification.svg";
import IconAsset51 from "../../../assets/icons/Icon-24-premium.svg";
import IconAsset52 from "../../../assets/icons/Icon-24-puzzle.svg";
import IconAsset53 from "../../../assets/icons/Icon-24-road-sign.svg";
import IconAsset54 from "../../../assets/icons/Icon-24-target.svg";
import IconAsset55 from "../../../assets/icons/Icon-3.svg";
import IconAsset56 from "../../../assets/icons/Icon.svg";
import IconAsset57 from "../../../assets/icons/Property 1=A.svg";
import IconAsset58 from "../../../assets/icons/Property 1=A1.svg";
import IconAsset59 from "../../../assets/icons/Property 1=A2.svg";
import IconAsset60 from "../../../assets/icons/Property 1=AM.svg";
import IconAsset61 from "../../../assets/icons/Property 1=B.svg";
import IconAsset62 from "../../../assets/icons/Property 1=B1.svg";
import IconAsset63 from "../../../assets/icons/Property 1=C.svg";
import IconAsset64 from "../../../assets/icons/Property 1=C1.svg";
import IconAsset65 from "../../../assets/icons/Property 1=D.svg";
import IconAsset66 from "../../../assets/icons/Property 1=D1.svg";
import IconAsset67 from "../../../assets/icons/Property 1=cabriolet 1.svg";
import IconAsset68 from "../../../assets/icons/Property 1=classic 1.svg";
import IconAsset69 from "../../../assets/icons/Property 1=crossover 1.svg";
import IconAsset70 from "../../../assets/icons/Property 1=hatchback 1.svg";
import IconAsset71 from "../../../assets/icons/Property 1=jeep 1.svg";
import IconAsset72 from "../../../assets/icons/Property 1=limousine 1.svg";
import IconAsset73 from "../../../assets/icons/Property 1=micro car 1.svg";
import IconAsset74 from "../../../assets/icons/Property 1=pick up 1.svg";
import IconAsset75 from "../../../assets/icons/Property 1=sedan 1.svg";
import IconAsset76 from "../../../assets/icons/Property 1=sportcar 1.svg";
import IconAsset77 from "../../../assets/icons/Property 1=suv 1.svg";
import IconAsset78 from "../../../assets/icons/State=Active.svg";
import IconAsset79 from "../../../assets/icons/State=Default.svg";
import IconAsset80 from "../../../assets/icons/icon-24-idea.svg";
import IconAsset81 from "../../../assets/icons/icon-24-random.svg";
import IconAsset82 from "../../../assets/icons/icon-24-updated.svg";

export type IconName =
  | "icon1"
  | "arrow"
  | "bulletCorrect"
  | "bulletDot"
  | "bulletWrong"
  | "info"
  | "premiumSmall"
  | "icon2"
  | "ai"
  | "alert"
  | "back"
  | "basket"
  | "bolt"
  | "book"
  | "calendar"
  | "check"
  | "checkbox"
  | "chevron"
  | "close"
  | "download"
  | "exam"
  | "flag"
  | "home"
  | "language"
  | "like"
  | "lock"
  | "map"
  | "moon"
  | "play"
  | "problem"
  | "profile"
  | "repeat"
  | "replay"
  | "search"
  | "star"
  | "start"
  | "sun"
  | "timer"
  | "trainer"
  | "trend"
  | "warning"
  | "zoom"
  | "brain"
  | "chart"
  | "checkmark"
  | "cup"
  | "document"
  | "flame"
  | "list"
  | "new"
  | "notification"
  | "premium"
  | "puzzle"
  | "roadSign"
  | "target"
  | "icon3"
  | "default"
  | "a"
  | "a1"
  | "a2"
  | "aM"
  | "b"
  | "b1"
  | "c"
  | "c1"
  | "d"
  | "d1"
  | "cabriolet"
  | "classic"
  | "crossover"
  | "hatchback"
  | "jeep"
  | "limousine"
  | "microCar"
  | "pickUp"
  | "sedan"
  | "sportcar"
  | "suv"
  | "stateActive"
  | "stateDefault"
  | "idea"
  | "random"
  | "updated";

export type IconComponent = FC<SvgProps>;

export const iconRegistry: Record<IconName, IconComponent> = {
  icon1: IconAsset0,
  arrow: IconAsset1,
  bulletCorrect: IconAsset2,
  bulletDot: IconAsset3,
  bulletWrong: IconAsset4,
  info: IconAsset5,
  premiumSmall: IconAsset6,
  icon2: IconAsset7,
  ai: IconAsset8,
  alert: IconAsset9,
  back: IconAsset10,
  basket: IconAsset11,
  bolt: IconAsset12,
  book: IconAsset13,
  calendar: IconAsset14,
  check: IconAsset15,
  checkbox: IconAsset16,
  chevron: IconAsset17,
  close: IconAsset18,
  download: IconAsset19,
  exam: IconAsset20,
  flag: IconAsset21,
  home: IconAsset22,
  language: IconAsset23,
  like: IconAsset24,
  lock: IconAsset25,
  map: IconAsset26,
  moon: IconAsset27,
  play: IconAsset28,
  problem: IconAsset29,
  profile: IconAsset30,
  repeat: IconAsset31,
  replay: IconAsset32,
  search: IconAsset33,
  star: IconAsset34,
  start: IconAsset35,
  sun: IconAsset36,
  timer: IconAsset37,
  trainer: IconAsset38,
  trend: IconAsset39,
  warning: IconAsset40,
  zoom: IconAsset41,
  brain: IconAsset42,
  chart: IconAsset43,
  checkmark: IconAsset44,
  cup: IconAsset45,
  document: IconAsset46,
  flame: IconAsset47,
  list: IconAsset48,
  new: IconAsset49,
  notification: IconAsset50,
  premium: IconAsset51,
  puzzle: IconAsset52,
  roadSign: IconAsset53,
  target: IconAsset54,
  icon3: IconAsset55,
  default: IconAsset56,
  a: IconAsset57,
  a1: IconAsset58,
  a2: IconAsset59,
  aM: IconAsset60,
  b: IconAsset61,
  b1: IconAsset62,
  c: IconAsset63,
  c1: IconAsset64,
  d: IconAsset65,
  d1: IconAsset66,
  cabriolet: IconAsset67,
  classic: IconAsset68,
  crossover: IconAsset69,
  hatchback: IconAsset70,
  jeep: IconAsset71,
  limousine: IconAsset72,
  microCar: IconAsset73,
  pickUp: IconAsset74,
  sedan: IconAsset75,
  sportcar: IconAsset76,
  suv: IconAsset77,
  stateActive: IconAsset78,
  stateDefault: IconAsset79,
  idea: IconAsset80,
  random: IconAsset81,
  updated: IconAsset82,
};
