/* eslint-disable import/no-unresolved */
/* This file is generated by scripts/generate-road-signs-content.mjs */

import type { ComponentType } from "react";
import type { SvgProps } from "react-native-svg";

import PlRoadSignAsset0 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-1.svg";
import PlRoadSignAsset1 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-2.svg";
import PlRoadSignAsset2 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-3.svg";
import PlRoadSignAsset3 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-4.svg";
import PlRoadSignAsset4 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-5.svg";
import PlRoadSignAsset5 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-6a.svg";
import PlRoadSignAsset6 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-6b.svg";
import PlRoadSignAsset7 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-6c.svg";
import PlRoadSignAsset8 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-6d.svg";
import PlRoadSignAsset9 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-6e.svg";
import PlRoadSignAsset10 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-7.svg";
import PlRoadSignAsset11 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-8.svg";
import PlRoadSignAsset12 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-9.svg";
import PlRoadSignAsset13 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-10.svg";
import PlRoadSignAsset14 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-11.svg";
import PlRoadSignAsset15 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-11a.svg";
import PlRoadSignAsset16 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-12a.svg";
import PlRoadSignAsset17 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-12b.svg";
import PlRoadSignAsset18 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-12c.svg";
import PlRoadSignAsset19 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-13.svg";
import PlRoadSignAsset20 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-14.svg";
import PlRoadSignAsset21 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-15.svg";
import PlRoadSignAsset22 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-16.svg";
import PlRoadSignAsset23 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-17.svg";
import PlRoadSignAsset24 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-18a.svg";
import PlRoadSignAsset25 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-18b.svg";
import PlRoadSignAsset26 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-19.svg";
import PlRoadSignAsset27 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-20.svg";
import PlRoadSignAsset28 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-21.svg";
import PlRoadSignAsset29 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-22.svg";
import PlRoadSignAsset30 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-23.svg";
import PlRoadSignAsset31 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-24.svg";
import PlRoadSignAsset32 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-25.svg";
import PlRoadSignAsset33 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-26.svg";
import PlRoadSignAsset34 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-27.svg";
import PlRoadSignAsset35 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-28.svg";
import PlRoadSignAsset36 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-29.svg";
import PlRoadSignAsset37 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-30.svg";
import PlRoadSignAsset38 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-31.svg";
import PlRoadSignAsset39 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-32.svg";
import PlRoadSignAsset40 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-33.svg";
import PlRoadSignAsset41 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_A-34.svg";
import PlRoadSignAsset42 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-1.svg";
import PlRoadSignAsset43 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-2.svg";
import PlRoadSignAsset44 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-3.svg";
import PlRoadSignAsset45 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-3-4.svg";
import PlRoadSignAsset46 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-3-4-10.svg";
import PlRoadSignAsset47 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-3a.svg";
import PlRoadSignAsset48 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-4.svg";
import PlRoadSignAsset49 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-5.svg";
import PlRoadSignAsset50 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-5-6t.svg";
import PlRoadSignAsset51 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-5-12t.svg";
import PlRoadSignAsset52 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-6.svg";
import PlRoadSignAsset53 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-6-8.svg";
import PlRoadSignAsset54 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-6-8-9.svg";
import PlRoadSignAsset55 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-7.svg";
import PlRoadSignAsset56 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-7-5t.svg";
import PlRoadSignAsset57 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-8.svg";
import PlRoadSignAsset58 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-9.svg";
import PlRoadSignAsset59 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-9-12.svg";
import PlRoadSignAsset60 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-10.svg";
import PlRoadSignAsset61 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-11.svg";
import PlRoadSignAsset62 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-12.svg";
import PlRoadSignAsset63 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-13.svg";
import PlRoadSignAsset64 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-13-14.svg";
import PlRoadSignAsset65 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-13a.svg";
import PlRoadSignAsset66 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-14.svg";
import PlRoadSignAsset67 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-15-2.0m.svg";
import PlRoadSignAsset68 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-16-3.1m.svg";
import PlRoadSignAsset69 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-16-3.2m.svg";
import PlRoadSignAsset70 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-16-3.4m.svg";
import PlRoadSignAsset71 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-16-3.5m.svg";
import PlRoadSignAsset72 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-17-6m.svg";
import PlRoadSignAsset73 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-18-3.5t.svg";
import PlRoadSignAsset74 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-18-7t.svg";
import PlRoadSignAsset75 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-19-10t.svg";
import PlRoadSignAsset76 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-20.svg";
import PlRoadSignAsset77 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-21.svg";
import PlRoadSignAsset78 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-22.svg";
import PlRoadSignAsset79 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-23.svg";
import PlRoadSignAsset80 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-24.svg";
import PlRoadSignAsset81 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-25.svg";
import PlRoadSignAsset82 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-26.svg";
import PlRoadSignAsset83 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-27.svg";
import PlRoadSignAsset84 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-28.svg";
import PlRoadSignAsset85 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-29.svg";
import PlRoadSignAsset86 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-30.svg";
import PlRoadSignAsset87 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-31.svg";
import PlRoadSignAsset88 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32.svg";
import PlRoadSignAsset89 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32a.svg";
import PlRoadSignAsset90 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32b.svg";
import PlRoadSignAsset91 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32c.svg";
import PlRoadSignAsset92 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32d.svg";
import PlRoadSignAsset93 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32e.svg";
import PlRoadSignAsset94 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-32f.svg";
import PlRoadSignAsset95 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-33-50.svg";
import PlRoadSignAsset96 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-34-50.svg";
import PlRoadSignAsset97 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-35.svg";
import PlRoadSignAsset98 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-35a.svg";
import PlRoadSignAsset99 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-35b.svg";
import PlRoadSignAsset100 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-35c.svg";
import PlRoadSignAsset101 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-36.svg";
import PlRoadSignAsset102 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-37.svg";
import PlRoadSignAsset103 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-38.svg";
import PlRoadSignAsset104 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-39.svg";
import PlRoadSignAsset105 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-40.svg";
import PlRoadSignAsset106 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-41.svg";
import PlRoadSignAsset107 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-42.svg";
import PlRoadSignAsset108 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-43-30.svg";
import PlRoadSignAsset109 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_B-44-30.svg";
import PlRoadSignAsset110 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-1.svg";
import PlRoadSignAsset111 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-2.svg";
import PlRoadSignAsset112 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-3.svg";
import PlRoadSignAsset113 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-4.svg";
import PlRoadSignAsset114 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-5.svg";
import PlRoadSignAsset115 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-6.svg";
import PlRoadSignAsset116 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-7.svg";
import PlRoadSignAsset117 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-8.svg";
import PlRoadSignAsset118 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-9.svg";
import PlRoadSignAsset119 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-10.svg";
import PlRoadSignAsset120 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-11.svg";
import PlRoadSignAsset121 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-12.svg";
import PlRoadSignAsset122 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-13.svg";
import PlRoadSignAsset123 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-13-16.svg";
import PlRoadSignAsset124 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-13-16a.svg";
import PlRoadSignAsset125 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-13-16b.svg";
import PlRoadSignAsset126 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-13a.svg";
import PlRoadSignAsset127 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-14-30.svg";
import PlRoadSignAsset128 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-15-30.svg";
import PlRoadSignAsset129 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-16.svg";
import PlRoadSignAsset130 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-16a.svg";
import PlRoadSignAsset131 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-17-2.svg";
import PlRoadSignAsset132 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-18.svg";
import PlRoadSignAsset133 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_C-19.svg";
import PlRoadSignAsset134 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-1.svg";
import PlRoadSignAsset135 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-2.svg";
import PlRoadSignAsset136 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-3.svg";
import PlRoadSignAsset137 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-4a.svg";
import PlRoadSignAsset138 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-4b.svg";
import PlRoadSignAsset139 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-4c.svg";
import PlRoadSignAsset140 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-5.svg";
import PlRoadSignAsset141 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-6.svg";
import PlRoadSignAsset142 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-6a.svg";
import PlRoadSignAsset143 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-6b.svg";
import PlRoadSignAsset144 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-7.svg";
import PlRoadSignAsset145 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-8.svg";
import PlRoadSignAsset146 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-9.svg";
import PlRoadSignAsset147 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-10.svg";
import PlRoadSignAsset148 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-11.svg";
import PlRoadSignAsset149 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-12.svg";
import PlRoadSignAsset150 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-13.svg";
import PlRoadSignAsset151 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-13a.svg";
import PlRoadSignAsset152 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-13b.svg";
import PlRoadSignAsset153 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-14.svg";
import PlRoadSignAsset154 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-15.svg";
import PlRoadSignAsset155 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-16.svg";
import PlRoadSignAsset156 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-17.svg";
import PlRoadSignAsset157 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-18.svg";
import PlRoadSignAsset158 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-18a.svg";
import PlRoadSignAsset159 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-18b.svg";
import PlRoadSignAsset160 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-19.svg";
import PlRoadSignAsset161 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-19a.svg";
import PlRoadSignAsset162 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-20.svg";
import PlRoadSignAsset163 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-20a.svg";
import PlRoadSignAsset164 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-21.svg";
import PlRoadSignAsset165 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-21a.svg";
import PlRoadSignAsset166 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-22.svg";
import PlRoadSignAsset167 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-23.svg";
import PlRoadSignAsset168 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-23a.svg";
import PlRoadSignAsset169 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-23b.svg";
import PlRoadSignAsset170 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-23c.svg";
import PlRoadSignAsset171 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-24.svg";
import PlRoadSignAsset172 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-25.svg";
import PlRoadSignAsset173 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-26.svg";
import PlRoadSignAsset174 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-26a.svg";
import PlRoadSignAsset175 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-26b.svg";
import PlRoadSignAsset176 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-26c.svg";
import PlRoadSignAsset177 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-26d.svg";
import PlRoadSignAsset178 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-27.svg";
import PlRoadSignAsset179 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-28.svg";
import PlRoadSignAsset180 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-29.svg";
import PlRoadSignAsset181 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-30.svg";
import PlRoadSignAsset182 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-31.svg";
import PlRoadSignAsset183 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-32.svg";
import PlRoadSignAsset184 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-33.svg";
import PlRoadSignAsset185 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-34.svg";
import PlRoadSignAsset186 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-34a.svg";
import PlRoadSignAsset187 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-34b.svg";
import PlRoadSignAsset188 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-34b_(alternative).svg";
import PlRoadSignAsset189 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-35.svg";
import PlRoadSignAsset190 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-35a.svg";
import PlRoadSignAsset191 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-36.svg";
import PlRoadSignAsset192 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-36a.svg";
import PlRoadSignAsset193 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-37.svg";
import PlRoadSignAsset194 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-38.svg";
import PlRoadSignAsset195 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-39a.svg";
import PlRoadSignAsset196 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-40.svg";
import PlRoadSignAsset197 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-41.svg";
import PlRoadSignAsset198 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-42.svg";
import PlRoadSignAsset199 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-43.svg";
import PlRoadSignAsset200 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-44.svg";
import PlRoadSignAsset201 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-45.svg";
import PlRoadSignAsset202 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-46.svg";
import PlRoadSignAsset203 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-47.svg";
import PlRoadSignAsset204 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-48.svg";
import PlRoadSignAsset205 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-48a.svg";
import PlRoadSignAsset206 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-49.svg";
import PlRoadSignAsset207 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-50.svg";
import PlRoadSignAsset208 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-51.svg";
import PlRoadSignAsset209 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-51aa.svg";
import PlRoadSignAsset210 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-51ab.svg";
import PlRoadSignAsset211 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-51b.svg";
import PlRoadSignAsset212 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-52.svg";
import PlRoadSignAsset213 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-53.svg";
import PlRoadSignAsset214 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-54.svg";
import PlRoadSignAsset215 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_D-55.svg";
import PlRoadSignAsset216 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-1.svg";
import PlRoadSignAsset217 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-2.svg";
import PlRoadSignAsset218 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-2a.svg";
import PlRoadSignAsset219 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-3.svg";
import PlRoadSignAsset220 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-3a.svg";
import PlRoadSignAsset221 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-3b.svg";
import PlRoadSignAsset222 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-3c.svg";
import PlRoadSignAsset223 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-4.svg";
import PlRoadSignAsset224 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-5.svg";
import PlRoadSignAsset225 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-6.svg";
import PlRoadSignAsset226 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-6a.svg";
import PlRoadSignAsset227 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-7.svg";
import PlRoadSignAsset228 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-8.svg";
import PlRoadSignAsset229 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-9.svg";
import PlRoadSignAsset230 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-10.svg";
import PlRoadSignAsset231 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-11d.svg";
import PlRoadSignAsset232 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-12a.svg";
import PlRoadSignAsset233 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-13a.svg";
import PlRoadSignAsset234 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-14a.svg";
import PlRoadSignAsset235 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-14b.svg";
import PlRoadSignAsset236 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-14c.svg";
import PlRoadSignAsset237 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-14d.svg";
import PlRoadSignAsset238 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-14e.svg";
import PlRoadSignAsset239 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-14f.svg";
import PlRoadSignAsset240 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-15a.svg";
import PlRoadSignAsset241 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-16.svg";
import PlRoadSignAsset242 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-17.svg";
import PlRoadSignAsset243 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-18.svg";
import PlRoadSignAsset244 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-19.svg";
import PlRoadSignAsset245 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-20.svg";
import PlRoadSignAsset246 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-21.svg";
import PlRoadSignAsset247 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_F-22.svg";
import PlRoadSignAsset248 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-1a.svg";
import PlRoadSignAsset249 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-1b.svg";
import PlRoadSignAsset250 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-1c.svg";
import PlRoadSignAsset251 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-1d.svg";
import PlRoadSignAsset252 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-1e.svg";
import PlRoadSignAsset253 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-1f.svg";
import PlRoadSignAsset254 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-2.svg";
import PlRoadSignAsset255 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-3.svg";
import PlRoadSignAsset256 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_G-4.svg";
import PlRoadSignAsset257 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-1.svg";
import PlRoadSignAsset258 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-1a.svg";
import PlRoadSignAsset259 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-1b.svg";
import PlRoadSignAsset260 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-2.svg";
import PlRoadSignAsset261 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-3.svg";
import PlRoadSignAsset262 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-3a.svg";
import PlRoadSignAsset263 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-4.svg";
import PlRoadSignAsset264 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-5.svg";
import PlRoadSignAsset265 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-6a.svg";
import PlRoadSignAsset266 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-6b.svg";
import PlRoadSignAsset267 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-6c.svg";
import PlRoadSignAsset268 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-6d.svg";
import PlRoadSignAsset269 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-7.svg";
import PlRoadSignAsset270 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-8.svg";
import PlRoadSignAsset271 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-9.svg";
import PlRoadSignAsset272 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-10.svg";
import PlRoadSignAsset273 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-11.svg";
import PlRoadSignAsset274 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-12.svg";
import PlRoadSignAsset275 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-13.svg";
import PlRoadSignAsset276 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-14.svg";
import PlRoadSignAsset277 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-14a.svg";
import PlRoadSignAsset278 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-14b.svg";
import PlRoadSignAsset279 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-14c.svg";
import PlRoadSignAsset280 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-14d.svg";
import PlRoadSignAsset281 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-15.svg";
import PlRoadSignAsset282 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-16.svg";
import PlRoadSignAsset283 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-16a.svg";
import PlRoadSignAsset284 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-17.svg";
import PlRoadSignAsset285 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-18.svg";
import PlRoadSignAsset286 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-18a.svg";
import PlRoadSignAsset287 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-18b.svg";
import PlRoadSignAsset288 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-18c.svg";
import PlRoadSignAsset289 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-19.svg";
import PlRoadSignAsset290 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-20.svg";
import PlRoadSignAsset291 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-21.svg";
import PlRoadSignAsset292 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-22.svg";
import PlRoadSignAsset293 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23a.svg";
import PlRoadSignAsset294 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23b.svg";
import PlRoadSignAsset295 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23c.svg";
import PlRoadSignAsset296 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23d.svg";
import PlRoadSignAsset297 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23e.svg";
import PlRoadSignAsset298 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23f.svg";
import PlRoadSignAsset299 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23g.svg";
import PlRoadSignAsset300 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23h.svg";
import PlRoadSignAsset301 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23i.svg";
import PlRoadSignAsset302 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-23j.svg";
import PlRoadSignAsset303 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-24.svg";
import PlRoadSignAsset304 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-25b.svg";
import PlRoadSignAsset305 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-25c.svg";
import PlRoadSignAsset306 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-26.svg";
import PlRoadSignAsset307 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-27.svg";
import PlRoadSignAsset308 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-28.svg";
import PlRoadSignAsset309 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-28a.svg";
import PlRoadSignAsset310 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-29.svg";
import PlRoadSignAsset311 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30a.svg";
import PlRoadSignAsset312 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30b.svg";
import PlRoadSignAsset313 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30c.svg";
import PlRoadSignAsset314 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30d.svg";
import PlRoadSignAsset315 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30e.svg";
import PlRoadSignAsset316 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30f.svg";
import PlRoadSignAsset317 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30g.svg";
import PlRoadSignAsset318 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30h.svg";
import PlRoadSignAsset319 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-30i.svg";
import PlRoadSignAsset320 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-31a.svg";
import PlRoadSignAsset321 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-31b.svg";
import PlRoadSignAsset322 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-31c.svg";
import PlRoadSignAsset323 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-31d.svg";
import PlRoadSignAsset324 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-31e.svg";
import PlRoadSignAsset325 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-32.svg";
import PlRoadSignAsset326 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-33.svg";
import PlRoadSignAsset327 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_T-34.svg";
import PlRoadSignAsset328 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-1.svg";
import PlRoadSignAsset329 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-2.svg";
import PlRoadSignAsset330 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-3.svg";
import PlRoadSignAsset331 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-4.svg";
import PlRoadSignAsset332 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-5.svg";
import PlRoadSignAsset333 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-6.svg";
import PlRoadSignAsset334 from "../../../../assets/pl-road-signs-wikimedia/PL_road_sign_W-7.svg";

export type SignAssetKey =
  | "A-1"
  | "A-2"
  | "A-3"
  | "A-4"
  | "A-5"
  | "A-6a"
  | "A-6b"
  | "A-6c"
  | "A-6d"
  | "A-6e"
  | "A-7"
  | "A-8"
  | "A-9"
  | "A-10"
  | "A-11"
  | "A-11a"
  | "A-12a"
  | "A-12b"
  | "A-12c"
  | "A-13"
  | "A-14"
  | "A-15"
  | "A-16"
  | "A-17"
  | "A-18a"
  | "A-18b"
  | "A-19"
  | "A-20"
  | "A-21"
  | "A-22"
  | "A-23"
  | "A-24"
  | "A-25"
  | "A-26"
  | "A-27"
  | "A-28"
  | "A-29"
  | "A-30"
  | "A-31"
  | "A-32"
  | "A-33"
  | "A-34"
  | "B-1"
  | "B-2"
  | "B-3"
  | "B-3-4"
  | "B-3-4-10"
  | "B-3a"
  | "B-4"
  | "B-5"
  | "B-5-6t"
  | "B-5-12t"
  | "B-6"
  | "B-6-8"
  | "B-6-8-9"
  | "B-7"
  | "B-7-5t"
  | "B-8"
  | "B-9"
  | "B-9-12"
  | "B-10"
  | "B-11"
  | "B-12"
  | "B-13"
  | "B-13-14"
  | "B-13a"
  | "B-14"
  | "B-15-2.0m"
  | "B-16-3.1m"
  | "B-16-3.2m"
  | "B-16-3.4m"
  | "B-16-3.5m"
  | "B-17-6m"
  | "B-18-3.5t"
  | "B-18-7t"
  | "B-19-10t"
  | "B-20"
  | "B-21"
  | "B-22"
  | "B-23"
  | "B-24"
  | "B-25"
  | "B-26"
  | "B-27"
  | "B-28"
  | "B-29"
  | "B-30"
  | "B-31"
  | "B-32"
  | "B-32a"
  | "B-32b"
  | "B-32c"
  | "B-32d"
  | "B-32e"
  | "B-32f"
  | "B-33-50"
  | "B-34-50"
  | "B-35"
  | "B-35a"
  | "B-35b"
  | "B-35c"
  | "B-36"
  | "B-37"
  | "B-38"
  | "B-39"
  | "B-40"
  | "B-41"
  | "B-42"
  | "B-43-30"
  | "B-44-30"
  | "C-1"
  | "C-2"
  | "C-3"
  | "C-4"
  | "C-5"
  | "C-6"
  | "C-7"
  | "C-8"
  | "C-9"
  | "C-10"
  | "C-11"
  | "C-12"
  | "C-13"
  | "C-13-16"
  | "C-13-16a"
  | "C-13-16b"
  | "C-13a"
  | "C-14-30"
  | "C-15-30"
  | "C-16"
  | "C-16a"
  | "C-17-2"
  | "C-18"
  | "C-19"
  | "D-1"
  | "D-2"
  | "D-3"
  | "D-4a"
  | "D-4b"
  | "D-4c"
  | "D-5"
  | "D-6"
  | "D-6a"
  | "D-6b"
  | "D-7"
  | "D-8"
  | "D-9"
  | "D-10"
  | "D-11"
  | "D-12"
  | "D-13"
  | "D-13a"
  | "D-13b"
  | "D-14"
  | "D-15"
  | "D-16"
  | "D-17"
  | "D-18"
  | "D-18a"
  | "D-18b"
  | "D-19"
  | "D-19a"
  | "D-20"
  | "D-20a"
  | "D-21"
  | "D-21a"
  | "D-22"
  | "D-23"
  | "D-23a"
  | "D-23b"
  | "D-23c"
  | "D-24"
  | "D-25"
  | "D-26"
  | "D-26a"
  | "D-26b"
  | "D-26c"
  | "D-26d"
  | "D-27"
  | "D-28"
  | "D-29"
  | "D-30"
  | "D-31"
  | "D-32"
  | "D-33"
  | "D-34"
  | "D-34a"
  | "D-34b"
  | "D-34b_(alternative)"
  | "D-35"
  | "D-35a"
  | "D-36"
  | "D-36a"
  | "D-37"
  | "D-38"
  | "D-39a"
  | "D-40"
  | "D-41"
  | "D-42"
  | "D-43"
  | "D-44"
  | "D-45"
  | "D-46"
  | "D-47"
  | "D-48"
  | "D-48a"
  | "D-49"
  | "D-50"
  | "D-51"
  | "D-51aa"
  | "D-51ab"
  | "D-51b"
  | "D-52"
  | "D-53"
  | "D-54"
  | "D-55"
  | "F-1"
  | "F-2"
  | "F-2a"
  | "F-3"
  | "F-3a"
  | "F-3b"
  | "F-3c"
  | "F-4"
  | "F-5"
  | "F-6"
  | "F-6a"
  | "F-7"
  | "F-8"
  | "F-9"
  | "F-10"
  | "F-11d"
  | "F-12a"
  | "F-13a"
  | "F-14a"
  | "F-14b"
  | "F-14c"
  | "F-14d"
  | "F-14e"
  | "F-14f"
  | "F-15a"
  | "F-16"
  | "F-17"
  | "F-18"
  | "F-19"
  | "F-20"
  | "F-21"
  | "F-22"
  | "G-1a"
  | "G-1b"
  | "G-1c"
  | "G-1d"
  | "G-1e"
  | "G-1f"
  | "G-2"
  | "G-3"
  | "G-4"
  | "T-1"
  | "T-1a"
  | "T-1b"
  | "T-2"
  | "T-3"
  | "T-3a"
  | "T-4"
  | "T-5"
  | "T-6a"
  | "T-6b"
  | "T-6c"
  | "T-6d"
  | "T-7"
  | "T-8"
  | "T-9"
  | "T-10"
  | "T-11"
  | "T-12"
  | "T-13"
  | "T-14"
  | "T-14a"
  | "T-14b"
  | "T-14c"
  | "T-14d"
  | "T-15"
  | "T-16"
  | "T-16a"
  | "T-17"
  | "T-18"
  | "T-18a"
  | "T-18b"
  | "T-18c"
  | "T-19"
  | "T-20"
  | "T-21"
  | "T-22"
  | "T-23a"
  | "T-23b"
  | "T-23c"
  | "T-23d"
  | "T-23e"
  | "T-23f"
  | "T-23g"
  | "T-23h"
  | "T-23i"
  | "T-23j"
  | "T-24"
  | "T-25b"
  | "T-25c"
  | "T-26"
  | "T-27"
  | "T-28"
  | "T-28a"
  | "T-29"
  | "T-30a"
  | "T-30b"
  | "T-30c"
  | "T-30d"
  | "T-30e"
  | "T-30f"
  | "T-30g"
  | "T-30h"
  | "T-30i"
  | "T-31a"
  | "T-31b"
  | "T-31c"
  | "T-31d"
  | "T-31e"
  | "T-32"
  | "T-33"
  | "T-34"
  | "W-1"
  | "W-2"
  | "W-3"
  | "W-4"
  | "W-5"
  | "W-6"
  | "W-7";

export const generatedSignAssets: Record<SignAssetKey, ComponentType<SvgProps>> = {
  "A-1": PlRoadSignAsset0,
  "A-2": PlRoadSignAsset1,
  "A-3": PlRoadSignAsset2,
  "A-4": PlRoadSignAsset3,
  "A-5": PlRoadSignAsset4,
  "A-6a": PlRoadSignAsset5,
  "A-6b": PlRoadSignAsset6,
  "A-6c": PlRoadSignAsset7,
  "A-6d": PlRoadSignAsset8,
  "A-6e": PlRoadSignAsset9,
  "A-7": PlRoadSignAsset10,
  "A-8": PlRoadSignAsset11,
  "A-9": PlRoadSignAsset12,
  "A-10": PlRoadSignAsset13,
  "A-11": PlRoadSignAsset14,
  "A-11a": PlRoadSignAsset15,
  "A-12a": PlRoadSignAsset16,
  "A-12b": PlRoadSignAsset17,
  "A-12c": PlRoadSignAsset18,
  "A-13": PlRoadSignAsset19,
  "A-14": PlRoadSignAsset20,
  "A-15": PlRoadSignAsset21,
  "A-16": PlRoadSignAsset22,
  "A-17": PlRoadSignAsset23,
  "A-18a": PlRoadSignAsset24,
  "A-18b": PlRoadSignAsset25,
  "A-19": PlRoadSignAsset26,
  "A-20": PlRoadSignAsset27,
  "A-21": PlRoadSignAsset28,
  "A-22": PlRoadSignAsset29,
  "A-23": PlRoadSignAsset30,
  "A-24": PlRoadSignAsset31,
  "A-25": PlRoadSignAsset32,
  "A-26": PlRoadSignAsset33,
  "A-27": PlRoadSignAsset34,
  "A-28": PlRoadSignAsset35,
  "A-29": PlRoadSignAsset36,
  "A-30": PlRoadSignAsset37,
  "A-31": PlRoadSignAsset38,
  "A-32": PlRoadSignAsset39,
  "A-33": PlRoadSignAsset40,
  "A-34": PlRoadSignAsset41,
  "B-1": PlRoadSignAsset42,
  "B-2": PlRoadSignAsset43,
  "B-3": PlRoadSignAsset44,
  "B-3-4": PlRoadSignAsset45,
  "B-3-4-10": PlRoadSignAsset46,
  "B-3a": PlRoadSignAsset47,
  "B-4": PlRoadSignAsset48,
  "B-5": PlRoadSignAsset49,
  "B-5-6t": PlRoadSignAsset50,
  "B-5-12t": PlRoadSignAsset51,
  "B-6": PlRoadSignAsset52,
  "B-6-8": PlRoadSignAsset53,
  "B-6-8-9": PlRoadSignAsset54,
  "B-7": PlRoadSignAsset55,
  "B-7-5t": PlRoadSignAsset56,
  "B-8": PlRoadSignAsset57,
  "B-9": PlRoadSignAsset58,
  "B-9-12": PlRoadSignAsset59,
  "B-10": PlRoadSignAsset60,
  "B-11": PlRoadSignAsset61,
  "B-12": PlRoadSignAsset62,
  "B-13": PlRoadSignAsset63,
  "B-13-14": PlRoadSignAsset64,
  "B-13a": PlRoadSignAsset65,
  "B-14": PlRoadSignAsset66,
  "B-15-2.0m": PlRoadSignAsset67,
  "B-16-3.1m": PlRoadSignAsset68,
  "B-16-3.2m": PlRoadSignAsset69,
  "B-16-3.4m": PlRoadSignAsset70,
  "B-16-3.5m": PlRoadSignAsset71,
  "B-17-6m": PlRoadSignAsset72,
  "B-18-3.5t": PlRoadSignAsset73,
  "B-18-7t": PlRoadSignAsset74,
  "B-19-10t": PlRoadSignAsset75,
  "B-20": PlRoadSignAsset76,
  "B-21": PlRoadSignAsset77,
  "B-22": PlRoadSignAsset78,
  "B-23": PlRoadSignAsset79,
  "B-24": PlRoadSignAsset80,
  "B-25": PlRoadSignAsset81,
  "B-26": PlRoadSignAsset82,
  "B-27": PlRoadSignAsset83,
  "B-28": PlRoadSignAsset84,
  "B-29": PlRoadSignAsset85,
  "B-30": PlRoadSignAsset86,
  "B-31": PlRoadSignAsset87,
  "B-32": PlRoadSignAsset88,
  "B-32a": PlRoadSignAsset89,
  "B-32b": PlRoadSignAsset90,
  "B-32c": PlRoadSignAsset91,
  "B-32d": PlRoadSignAsset92,
  "B-32e": PlRoadSignAsset93,
  "B-32f": PlRoadSignAsset94,
  "B-33-50": PlRoadSignAsset95,
  "B-34-50": PlRoadSignAsset96,
  "B-35": PlRoadSignAsset97,
  "B-35a": PlRoadSignAsset98,
  "B-35b": PlRoadSignAsset99,
  "B-35c": PlRoadSignAsset100,
  "B-36": PlRoadSignAsset101,
  "B-37": PlRoadSignAsset102,
  "B-38": PlRoadSignAsset103,
  "B-39": PlRoadSignAsset104,
  "B-40": PlRoadSignAsset105,
  "B-41": PlRoadSignAsset106,
  "B-42": PlRoadSignAsset107,
  "B-43-30": PlRoadSignAsset108,
  "B-44-30": PlRoadSignAsset109,
  "C-1": PlRoadSignAsset110,
  "C-2": PlRoadSignAsset111,
  "C-3": PlRoadSignAsset112,
  "C-4": PlRoadSignAsset113,
  "C-5": PlRoadSignAsset114,
  "C-6": PlRoadSignAsset115,
  "C-7": PlRoadSignAsset116,
  "C-8": PlRoadSignAsset117,
  "C-9": PlRoadSignAsset118,
  "C-10": PlRoadSignAsset119,
  "C-11": PlRoadSignAsset120,
  "C-12": PlRoadSignAsset121,
  "C-13": PlRoadSignAsset122,
  "C-13-16": PlRoadSignAsset123,
  "C-13-16a": PlRoadSignAsset124,
  "C-13-16b": PlRoadSignAsset125,
  "C-13a": PlRoadSignAsset126,
  "C-14-30": PlRoadSignAsset127,
  "C-15-30": PlRoadSignAsset128,
  "C-16": PlRoadSignAsset129,
  "C-16a": PlRoadSignAsset130,
  "C-17-2": PlRoadSignAsset131,
  "C-18": PlRoadSignAsset132,
  "C-19": PlRoadSignAsset133,
  "D-1": PlRoadSignAsset134,
  "D-2": PlRoadSignAsset135,
  "D-3": PlRoadSignAsset136,
  "D-4a": PlRoadSignAsset137,
  "D-4b": PlRoadSignAsset138,
  "D-4c": PlRoadSignAsset139,
  "D-5": PlRoadSignAsset140,
  "D-6": PlRoadSignAsset141,
  "D-6a": PlRoadSignAsset142,
  "D-6b": PlRoadSignAsset143,
  "D-7": PlRoadSignAsset144,
  "D-8": PlRoadSignAsset145,
  "D-9": PlRoadSignAsset146,
  "D-10": PlRoadSignAsset147,
  "D-11": PlRoadSignAsset148,
  "D-12": PlRoadSignAsset149,
  "D-13": PlRoadSignAsset150,
  "D-13a": PlRoadSignAsset151,
  "D-13b": PlRoadSignAsset152,
  "D-14": PlRoadSignAsset153,
  "D-15": PlRoadSignAsset154,
  "D-16": PlRoadSignAsset155,
  "D-17": PlRoadSignAsset156,
  "D-18": PlRoadSignAsset157,
  "D-18a": PlRoadSignAsset158,
  "D-18b": PlRoadSignAsset159,
  "D-19": PlRoadSignAsset160,
  "D-19a": PlRoadSignAsset161,
  "D-20": PlRoadSignAsset162,
  "D-20a": PlRoadSignAsset163,
  "D-21": PlRoadSignAsset164,
  "D-21a": PlRoadSignAsset165,
  "D-22": PlRoadSignAsset166,
  "D-23": PlRoadSignAsset167,
  "D-23a": PlRoadSignAsset168,
  "D-23b": PlRoadSignAsset169,
  "D-23c": PlRoadSignAsset170,
  "D-24": PlRoadSignAsset171,
  "D-25": PlRoadSignAsset172,
  "D-26": PlRoadSignAsset173,
  "D-26a": PlRoadSignAsset174,
  "D-26b": PlRoadSignAsset175,
  "D-26c": PlRoadSignAsset176,
  "D-26d": PlRoadSignAsset177,
  "D-27": PlRoadSignAsset178,
  "D-28": PlRoadSignAsset179,
  "D-29": PlRoadSignAsset180,
  "D-30": PlRoadSignAsset181,
  "D-31": PlRoadSignAsset182,
  "D-32": PlRoadSignAsset183,
  "D-33": PlRoadSignAsset184,
  "D-34": PlRoadSignAsset185,
  "D-34a": PlRoadSignAsset186,
  "D-34b": PlRoadSignAsset187,
  "D-34b_(alternative)": PlRoadSignAsset188,
  "D-35": PlRoadSignAsset189,
  "D-35a": PlRoadSignAsset190,
  "D-36": PlRoadSignAsset191,
  "D-36a": PlRoadSignAsset192,
  "D-37": PlRoadSignAsset193,
  "D-38": PlRoadSignAsset194,
  "D-39a": PlRoadSignAsset195,
  "D-40": PlRoadSignAsset196,
  "D-41": PlRoadSignAsset197,
  "D-42": PlRoadSignAsset198,
  "D-43": PlRoadSignAsset199,
  "D-44": PlRoadSignAsset200,
  "D-45": PlRoadSignAsset201,
  "D-46": PlRoadSignAsset202,
  "D-47": PlRoadSignAsset203,
  "D-48": PlRoadSignAsset204,
  "D-48a": PlRoadSignAsset205,
  "D-49": PlRoadSignAsset206,
  "D-50": PlRoadSignAsset207,
  "D-51": PlRoadSignAsset208,
  "D-51aa": PlRoadSignAsset209,
  "D-51ab": PlRoadSignAsset210,
  "D-51b": PlRoadSignAsset211,
  "D-52": PlRoadSignAsset212,
  "D-53": PlRoadSignAsset213,
  "D-54": PlRoadSignAsset214,
  "D-55": PlRoadSignAsset215,
  "F-1": PlRoadSignAsset216,
  "F-2": PlRoadSignAsset217,
  "F-2a": PlRoadSignAsset218,
  "F-3": PlRoadSignAsset219,
  "F-3a": PlRoadSignAsset220,
  "F-3b": PlRoadSignAsset221,
  "F-3c": PlRoadSignAsset222,
  "F-4": PlRoadSignAsset223,
  "F-5": PlRoadSignAsset224,
  "F-6": PlRoadSignAsset225,
  "F-6a": PlRoadSignAsset226,
  "F-7": PlRoadSignAsset227,
  "F-8": PlRoadSignAsset228,
  "F-9": PlRoadSignAsset229,
  "F-10": PlRoadSignAsset230,
  "F-11d": PlRoadSignAsset231,
  "F-12a": PlRoadSignAsset232,
  "F-13a": PlRoadSignAsset233,
  "F-14a": PlRoadSignAsset234,
  "F-14b": PlRoadSignAsset235,
  "F-14c": PlRoadSignAsset236,
  "F-14d": PlRoadSignAsset237,
  "F-14e": PlRoadSignAsset238,
  "F-14f": PlRoadSignAsset239,
  "F-15a": PlRoadSignAsset240,
  "F-16": PlRoadSignAsset241,
  "F-17": PlRoadSignAsset242,
  "F-18": PlRoadSignAsset243,
  "F-19": PlRoadSignAsset244,
  "F-20": PlRoadSignAsset245,
  "F-21": PlRoadSignAsset246,
  "F-22": PlRoadSignAsset247,
  "G-1a": PlRoadSignAsset248,
  "G-1b": PlRoadSignAsset249,
  "G-1c": PlRoadSignAsset250,
  "G-1d": PlRoadSignAsset251,
  "G-1e": PlRoadSignAsset252,
  "G-1f": PlRoadSignAsset253,
  "G-2": PlRoadSignAsset254,
  "G-3": PlRoadSignAsset255,
  "G-4": PlRoadSignAsset256,
  "T-1": PlRoadSignAsset257,
  "T-1a": PlRoadSignAsset258,
  "T-1b": PlRoadSignAsset259,
  "T-2": PlRoadSignAsset260,
  "T-3": PlRoadSignAsset261,
  "T-3a": PlRoadSignAsset262,
  "T-4": PlRoadSignAsset263,
  "T-5": PlRoadSignAsset264,
  "T-6a": PlRoadSignAsset265,
  "T-6b": PlRoadSignAsset266,
  "T-6c": PlRoadSignAsset267,
  "T-6d": PlRoadSignAsset268,
  "T-7": PlRoadSignAsset269,
  "T-8": PlRoadSignAsset270,
  "T-9": PlRoadSignAsset271,
  "T-10": PlRoadSignAsset272,
  "T-11": PlRoadSignAsset273,
  "T-12": PlRoadSignAsset274,
  "T-13": PlRoadSignAsset275,
  "T-14": PlRoadSignAsset276,
  "T-14a": PlRoadSignAsset277,
  "T-14b": PlRoadSignAsset278,
  "T-14c": PlRoadSignAsset279,
  "T-14d": PlRoadSignAsset280,
  "T-15": PlRoadSignAsset281,
  "T-16": PlRoadSignAsset282,
  "T-16a": PlRoadSignAsset283,
  "T-17": PlRoadSignAsset284,
  "T-18": PlRoadSignAsset285,
  "T-18a": PlRoadSignAsset286,
  "T-18b": PlRoadSignAsset287,
  "T-18c": PlRoadSignAsset288,
  "T-19": PlRoadSignAsset289,
  "T-20": PlRoadSignAsset290,
  "T-21": PlRoadSignAsset291,
  "T-22": PlRoadSignAsset292,
  "T-23a": PlRoadSignAsset293,
  "T-23b": PlRoadSignAsset294,
  "T-23c": PlRoadSignAsset295,
  "T-23d": PlRoadSignAsset296,
  "T-23e": PlRoadSignAsset297,
  "T-23f": PlRoadSignAsset298,
  "T-23g": PlRoadSignAsset299,
  "T-23h": PlRoadSignAsset300,
  "T-23i": PlRoadSignAsset301,
  "T-23j": PlRoadSignAsset302,
  "T-24": PlRoadSignAsset303,
  "T-25b": PlRoadSignAsset304,
  "T-25c": PlRoadSignAsset305,
  "T-26": PlRoadSignAsset306,
  "T-27": PlRoadSignAsset307,
  "T-28": PlRoadSignAsset308,
  "T-28a": PlRoadSignAsset309,
  "T-29": PlRoadSignAsset310,
  "T-30a": PlRoadSignAsset311,
  "T-30b": PlRoadSignAsset312,
  "T-30c": PlRoadSignAsset313,
  "T-30d": PlRoadSignAsset314,
  "T-30e": PlRoadSignAsset315,
  "T-30f": PlRoadSignAsset316,
  "T-30g": PlRoadSignAsset317,
  "T-30h": PlRoadSignAsset318,
  "T-30i": PlRoadSignAsset319,
  "T-31a": PlRoadSignAsset320,
  "T-31b": PlRoadSignAsset321,
  "T-31c": PlRoadSignAsset322,
  "T-31d": PlRoadSignAsset323,
  "T-31e": PlRoadSignAsset324,
  "T-32": PlRoadSignAsset325,
  "T-33": PlRoadSignAsset326,
  "T-34": PlRoadSignAsset327,
  "W-1": PlRoadSignAsset328,
  "W-2": PlRoadSignAsset329,
  "W-3": PlRoadSignAsset330,
  "W-4": PlRoadSignAsset331,
  "W-5": PlRoadSignAsset332,
  "W-6": PlRoadSignAsset333,
  "W-7": PlRoadSignAsset334,
};
