/* eslint-disable import/no-unresolved */
/* This file is generated by scripts/generate-road-signs-content.mjs */

import type { ImageSourcePropType } from "react-native";

export const generatedRasterSignAssets: Record<string, ImageSourcePropType> = {
  "E-17b": require("../../../../assets/pl-road-signs-wikimedia/PL_road_sign_E-17b.png"),
  "E-18b": require("../../../../assets/pl-road-signs-wikimedia/PL_road_sign_E-18b.png"),
};
